### ISSUE TITLE
Create a dashboard for the shop owner to manage him/her shop

### ISSUE THREAD

**Issue by rkdesai07** [rkdesai07/FlexiProductControl-Fe#6]
Header menu 
Business name
Business logo 
Right side login and profile button 

Menu

Manage users 
Manage business
View Statics
Manage products
Manage product category 

Default selection

View Statics

**Comment by maheshvadecha** [comment]
![userProfileManageLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/6bbc52f7-2731-485a-a209-84afe542ecf6)
![userProfileManageDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/30bdc471-dbf4-4c49-a2f8-9c9b71f5bf6e)
![signupPage](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/1ccbcb83-f6a9-4584-ab36-31c07e5576dd)
![signupLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/e8cf7d50-320d-4bf0-858a-3c2452634e00)
![Screenshot from 2023-12-30 15-19-51](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/169d31c2-a712-4bf8-9b4e-ed71df6a9a04)
![Screenshot from 2023-12-30 15-19-08](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/e406a2d2-668d-4da1-b0d5-82645d94541f)
![moblileDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/6e716fab-0b63-469d-9d18-ab7f881494fc)
![mobileMenuHideDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/ed1d7fce-16a0-46fe-89a3-ab48082e5578)
![mobileLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/bbcdbbe1-6b17-41fc-9c35-2e7d1fcc44eb)
![mobileHidemenuLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/198b3a6c-36c1-4d0b-b4a6-c0c3c66bba6c)
![mainpgeDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/796c7d3e-c2d6-4413-bfc6-7648a01295a5)
![mainPageLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/a687879d-ed58-44aa-b9b8-d797d1464d46)
![loginLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/33c24808-2e94-4ba1-8308-bef0439e57b6)
![homepageLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/342a2913-a641-454b-b30e-74c84b475a91)
![homepageDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/97e82d6e-c2af-4ac4-ab1c-b458cf82ee92)
![HideMenuLight](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/0fff4513-2e3b-4be4-8f50-f7806adb9114)
![hideMenuDark](https://github.com/rkdesai07/FlexiProductControl-Fe/assets/109420102/a8a0fb14-ecaa-4f71-95ca-dd300ce36bbd)


-Dashboard design for shop owner  done.
